# Generated by Django 2.2.28 on 2022-12-14 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=255, verbose_name='商品名')),
                ('price', models.CharField(blank=True, max_length=255, verbose_name='値段')),
                ('url', models.CharField(blank=True, max_length=255, verbose_name='URL')),
            ],
        ),
    ]
